#!/usr/bin/env python
# encoding: utf-8

import sys
sys.path.insert(0, sys.path[0]+'/waf_tools')

VERSION = '1.0.0'
APPNAME = 'omni_kinematics'

srcdir = 'src'
blddir = 'build'


def options(opt):
    opt.load('compiler_cxx')
    opt.load('eigen')


def configure(conf):
    conf.load('compiler_cxx')
    conf.load('eigen')

    conf.check_eigen(required=True)

    if conf.env.CXX_NAME in ["icc", "icpc"]:
        common_flags = "-Wall -std=c++11"
        opt_flags = " -O3 -xHost  -march=native -mtune=native -unroll -fma -g"
    elif conf.env.CXX_NAME in ["clang"]:
        common_flags = "-Wall -std=c++11"
        opt_flags = " -O3 -march=native -g"
    else:
        if int(conf.env.CC_VERSION[0] + conf.env.CC_VERSION[1]) < 47:
            common_flags = "-Wall -std=c++0x"
        else:
            common_flags = "-Wall -std=c++11"
        opt_flags = " -O3 -march=native -g"

    all_flags = common_flags + opt_flags
    conf.env['CXXFLAGS'] = conf.env['CXXFLAGS'] + all_flags.split(' ')


def build(bld):
    bld.program(features='cxxprogram',
                source='src/test.cpp',
                includes='include',
                uselib='EIGEN',
                target='omni_kinematics_test')

    bld.install_files('${PREFIX}/include/omni_kinematics', bld.path.ant_glob('include/omni_kinematics/*.hpp'), relative_trick=True)
